//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hui_WPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HF")]
        public string UserNamingParentDirText {
            get {
                return ((string)(this["UserNamingParentDirText"]));
            }
            set {
                this["UserNamingParentDirText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserNamingIncludeSubDir {
            get {
                return ((bool)(this["UserNamingIncludeSubDir"]));
            }
            set {
                this["UserNamingIncludeSubDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sF")]
        public string UserNamingSubDirText {
            get {
                return ((string)(this["UserNamingSubDirText"]));
            }
            set {
                this["UserNamingSubDirText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserNamingIncludeFileName {
            get {
                return ((bool)(this["UserNamingIncludeFileName"]));
            }
            set {
                this["UserNamingIncludeFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("File")]
        public string UserNamingFileNameText {
            get {
                return ((string)(this["UserNamingFileNameText"]));
            }
            set {
                this["UserNamingFileNameText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserEnableTimestamp {
            get {
                return ((bool)(this["UserEnableTimestamp"]));
            }
            set {
                this["UserEnableTimestamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyyMMdd_HHmmss_")]
        public string UserTimestampFormat {
            get {
                return ((string)(this["UserTimestampFormat"]));
            }
            set {
                this["UserTimestampFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserEnableCounter {
            get {
                return ((bool)(this["UserEnableCounter"]));
            }
            set {
                this["UserEnableCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D3")]
        public string UserCounterFormat {
            get {
                return ((string)(this["UserCounterFormat"]));
            }
            set {
                this["UserCounterFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int UserCounterStartValue {
            get {
                return ((int)(this["UserCounterStartValue"]));
            }
            set {
                this["UserCounterStartValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserNamingUseSeparator {
            get {
                return ((bool)(this["UserNamingUseSeparator"]));
            }
            set {
                this["UserNamingUseSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserOverwriteOutput {
            get {
                return ((bool)(this["UserOverwriteOutput"]));
            }
            set {
                this["UserOverwriteOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-")]
        public string UserNamingSeparator {
            get {
                return ((string)(this["UserNamingSeparator"]));
            }
            set {
                this["UserNamingSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Processed")]
        public string UserOutputSubfolder {
            get {
                return ((string)(this["UserOutputSubfolder"]));
            }
            set {
                this["UserOutputSubfolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserImageOutputPath {
            get {
                return ((string)(this["UserImageOutputPath"]));
            }
            set {
                this["UserImageOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserVideoOutputPath {
            get {
                return ((string)(this["UserVideoOutputPath"]));
            }
            set {
                this["UserVideoOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserBackupOutputPath {
            get {
                return ((string)(this["UserBackupOutputPath"]));
            }
            set {
                this["UserBackupOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserGeneralBackupPrefix {
            get {
                return ((string)(this["UserGeneralBackupPrefix"]));
            }
            set {
                this["UserGeneralBackupPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExifTool")]
        public string UserExifToolTag {
            get {
                return ((string)(this["UserExifToolTag"]));
            }
            set {
                this["UserExifToolTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserEnableBackup {
            get {
                return ((bool)(this["UserEnableBackup"]));
            }
            set {
                this["UserEnableBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JPEG")]
        public string UserOutputImageFormat {
            get {
                return ((string)(this["UserOutputImageFormat"]));
            }
            set {
                this["UserOutputImageFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int UserJpegQuality {
            get {
                return ((int)(this["UserJpegQuality"]));
            }
            set {
                this["UserJpegQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UserOriginalFileAction {
            get {
                return ((int)(this["UserOriginalFileAction"]));
            }
            set {
                this["UserOriginalFileAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("夹/父/子/名+时间戳+计数器")]
        public string GlobalNameOrder {
            get {
                return ((string)(this["GlobalNameOrder"]));
            }
            set {
                this["GlobalNameOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserUseTimestampSubfolderForMedia {
            get {
                return ((bool)(this["UserUseTimestampSubfolderForMedia"]));
            }
            set {
                this["UserUseTimestampSubfolderForMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zh")]
        public string UserLanguage {
            get {
                return ((string)(this["UserLanguage"]));
            }
            set {
                this["UserLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserGeneralRenamePrefix {
            get {
                return ((string)(this["UserGeneralRenamePrefix"]));
            }
            set {
                this["UserGeneralRenamePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserNamingIncludeFolder {
            get {
                return ((bool)(this["UserNamingIncludeFolder"]));
            }
            set {
                this["UserNamingIncludeFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FD")]
        public string UserNamingFolderText {
            get {
                return ((string)(this["UserNamingFolderText"]));
            }
            set {
                this["UserNamingFolderText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserNamingIncludeParentDir {
            get {
                return ((bool)(this["UserNamingIncludeParentDir"]));
            }
            set {
                this["UserNamingIncludeParentDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string 设置 {
            get {
                return ((string)(this["设置"]));
            }
            set {
                this["设置"] = value;
            }
        }
    }
}
